baseURL = 'http://jack-photoproject-2026.s3-website.eu-north-1.amazonaws.com/'
languageCode = 'en-us'
title = 'Jack Harding photography'
theme = 'gallery'

[[menu.main]]
    name = "Galleries"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2