baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jack Harding photography'
theme = 'gallery'

[[menu.main]]
    name = "Galleries"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2